[package]
name = "particle_detect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", features = ["derive"] }
image = "0.24.3"
imageproc = "0.23.0"
nalgebra = "0.31.0"
