threshold: 35
min_fitness: 0.3
dist_threshold: 2.0
radius_threshold: 6.0
min_contour_points: 50
max_contour_points: 2000
min_aspect_ratio: 1.3
max_aspect_ratio: 2.2
min_length: 55.0
max_length: 75.0
min_width: 30.0
max_width: 40.0
rotation_center_x: 1500
rotation_center_y: 1500
detect_radius_min: 800
detect_radius_max: 1450
