threshold: 35
min_fitness: 0.3
dist_threshold: 2.0
radius_threshold: 6.0
min_contour_points: 50
max_contour_points: 2000
min_aspect_ratio: 3.5
max_aspect_ratio: 4.2
min_length: 93.0
max_length: 104.0
min_width: 20.0
max_width: 35.0
rotation_center_x: 1505
rotation_center_y: 1485
detect_radius_min: 800
detect_radius_max: 1450
